### ISSUE TITLE
Style resources page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#82]
# Manta Ray done criteria
- [x] Title
- [x] Document type (with popup)
- [x] Published date
- [x] Last updated date
- [x] Summary (300 words max)
- [x] Section divide (for use within wysiwyg)
- [x] Section highlight style
- [x] Sticky RHS heading links (see #103 if needed)
- [x] References (with or without jump links)
- [x] You may also be interested in (related content) + see all link (based on topic and document type)
- [x] Other resources in this series (related content nugget should NOT appear if this nugget is being used)
- [x] Download (clicking image downloads document)
  - [x] Image downloads file
  - [x] Text title downloads file (as with rh nugget)
  - [x] If the resource appears in a series then there should be a second download link in the download RH box to enable the person to download the full series in one PDF
- [x] BGS happy with the size of the download image (may need reducing)
- [x]  feedback section #96
- [x]  author links #92 (To do on members directory sprint)
- [x]  resource series #102 
- [x]  tags #104
- [x]  members only links #101 

# Designs & Docs
- Design: https://invis.io/DQEPLPAY4
- Wireframe: https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528
- Content model: https://www.lucidchart.com/documents/edit/6745084e-6199-4704-98de-8cc6d5391298/0
- Drupal link: http://bgs-dev.mrmdev.co.uk/boxni-title-for-a-resource-item

**Comment by angievanhegan** [comment]
@russ-manta ready to be assigned to a dev

**Comment by angievanhegan** [comment]
@StephMSlack Are you happy to sign this off and move it to done? There are some small changes in the feedback section on card

**Comment by StephMSlack** [comment]
@angievanhegan - re: authors - at the moment it doesn't de-dupe authors so I have accidentally added the same author twice. Is there a way that we can avoid this happening? Not sure if this should link to #92?

**Comment by angievanhegan** [comment]
@StephMSlack I'll add this as a new issue which we can do if it's a quick one.
